//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CDLoadCommand.h"

@class NSArray, NSDictionary;

@interface CDLCSymbolTable : CDLoadCommand
{
    struct symtab_command _symtabCommand;
    NSArray *_symbols;
    unsigned long long _baseAddress;
    NSDictionary *_classSymbols;
    struct {
        unsigned int didFindBaseAddress:1;
        unsigned int didWarnAboutUnfoundBaseAddress:1;
        unsigned int _unused:30;
    } _flags;
}

@property(readonly, nonatomic) NSArray *symbols; // @synthesize symbols=_symbols;
- (void).cxx_destruct;
- (id)symbolForClassName:(id)arg1;
@property(readonly, nonatomic) unsigned long long baseAddress;
@property(readonly, nonatomic) unsigned int strsize;
@property(readonly, nonatomic) unsigned int stroff;
@property(readonly, nonatomic) unsigned int nsyms;
@property(readonly, nonatomic) unsigned int symoff;
- (void)loadSymbols;
- (unsigned int)cmdsize;
- (unsigned int)cmd;
- (id)extraDescription;
- (id)initWithDataCursor:(id)arg1;

@end

