//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class CDSearchPathState, CDTypeController, NSArray, NSMutableArray, NSMutableDictionary, NSRegularExpression, NSString;

@interface CDClassDump : NSObject
{
    CDSearchPathState *_searchPathState;
    BOOL _shouldProcessRecursively;
    BOOL _shouldSortClasses;
    BOOL _shouldSortClassesByInheritance;
    BOOL _shouldSortMethods;
    BOOL _shouldShowIvarOffsets;
    BOOL _shouldShowMethodAddresses;
    BOOL _shouldShowHeader;
    NSRegularExpression *_regularExpression;
    NSString *_sdkRoot;
    NSMutableArray *_machOFiles;
    NSMutableDictionary *_machOFilesByName;
    NSMutableArray *_objcProcessors;
    CDTypeController *_typeController;
    CDStruct_7a118b40 _targetArch;
}

@property(readonly) CDTypeController *typeController; // @synthesize typeController=_typeController;
@property CDStruct_7a118b40 targetArch; // @synthesize targetArch=_targetArch;
@property(readonly) NSArray *objcProcessors; // @synthesize objcProcessors=_objcProcessors;
@property(readonly) NSArray *machOFiles; // @synthesize machOFiles=_machOFiles;
@property(retain) NSString *sdkRoot; // @synthesize sdkRoot=_sdkRoot;
@property(retain) NSRegularExpression *regularExpression; // @synthesize regularExpression=_regularExpression;
@property BOOL shouldShowHeader; // @synthesize shouldShowHeader=_shouldShowHeader;
@property BOOL shouldShowMethodAddresses; // @synthesize shouldShowMethodAddresses=_shouldShowMethodAddresses;
@property BOOL shouldShowIvarOffsets; // @synthesize shouldShowIvarOffsets=_shouldShowIvarOffsets;
@property BOOL shouldSortMethods; // @synthesize shouldSortMethods=_shouldSortMethods;
@property BOOL shouldSortClassesByInheritance; // @synthesize shouldSortClassesByInheritance=_shouldSortClassesByInheritance;
@property BOOL shouldSortClasses; // @synthesize shouldSortClasses=_shouldSortClasses;
@property BOOL shouldProcessRecursively; // @synthesize shouldProcessRecursively=_shouldProcessRecursively;
@property(readonly) CDSearchPathState *searchPathState; // @synthesize searchPathState=_searchPathState;
- (void).cxx_destruct;
- (void)showLoadCommands;
- (void)showHeader;
- (void)registerTypes;
- (void)appendHeaderToString:(id)arg1;
- (id)machOFileWithName:(id)arg1;
- (void)recursivelyVisit:(id)arg1;
- (void)processObjectiveCData;
- (BOOL)loadFile:(id)arg1 error:(id *)arg2;
@property(readonly, nonatomic) BOOL hasObjectiveCRuntimeInfo;
@property(readonly, nonatomic) BOOL hasEncryptedFiles;
@property(readonly, nonatomic) BOOL containsObjectiveCData;
- (BOOL)shouldShowName:(id)arg1;
- (id)init;

@end

