//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCopying.h"

@class NSMutableArray, NSString;

@interface CDTypeName : NSObject <NSCopying>
{
    NSString *_name;
    NSMutableArray *_templateTypes;
    NSString *_suffix;
}

@property(retain) NSString *suffix; // @synthesize suffix=_suffix;
@property(readonly) NSMutableArray *templateTypes; // @synthesize templateTypes=_templateTypes;
@property(retain) NSString *name; // @synthesize name=_name;
- (void).cxx_destruct;
@property(readonly, nonatomic) BOOL isTemplateType;
- (id)description;
- (BOOL)isEqual:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)init;

@end

