//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableArray;

@interface CDOCSymtab : NSObject
{
    NSMutableArray *_classes;
    NSMutableArray *_categories;
}

@property(readonly) NSMutableArray *categories; // @synthesize categories=_categories;
@property(readonly) NSMutableArray *classes; // @synthesize classes=_classes;
- (void).cxx_destruct;
- (void)addCategory:(id)arg1;
- (void)addClass:(id)arg1;
- (id)description;
- (id)init;

@end

