//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CDFile.h"

@class NSArray, NSMutableArray;

@interface CDFatFile : CDFile
{
    NSMutableArray *_arches;
}

@property(readonly) NSMutableArray *arches; // @synthesize arches=_arches;
- (void).cxx_destruct;
- (BOOL)containsArchitecture:(CDStruct_7a118b40)arg1;
- (void)addArchitecture:(id)arg1;
- (id)architectureNameDescription;
@property(readonly, nonatomic) NSArray *archNames;
- (id)machOFileWithArch:(CDStruct_7a118b40)arg1;
- (id)fatArchWithArch:(CDStruct_7a118b40)arg1;
- (BOOL)bestMatchForArch:(CDStruct_7a118b40 *)arg1;
- (id)description;
- (id)initWithData:(id)arg1 filename:(id)arg2 searchPathState:(id)arg3;
- (id)init;

@end

