//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#pragma mark Named Structures

struct dyld_info_command {
    unsigned int cmd;
    unsigned int cmdsize;
    unsigned int rebase_off;
    unsigned int rebase_size;
    unsigned int bind_off;
    unsigned int bind_size;
    unsigned int weak_bind_off;
    unsigned int weak_bind_size;
    unsigned int lazy_bind_off;
    unsigned int lazy_bind_size;
    unsigned int export_off;
    unsigned int export_size;
};

struct dylib {
    union lc_str name;
    unsigned int timestamp;
    unsigned int current_version;
    unsigned int compatibility_version;
};

struct dylib_command {
    unsigned int cmd;
    unsigned int cmdsize;
    struct dylib dylib;
};

struct dylinker_command {
    unsigned int cmd;
    unsigned int cmdsize;
    union lc_str name;
};

struct dysymtab_command {
    unsigned int cmd;
    unsigned int cmdsize;
    unsigned int ilocalsym;
    unsigned int nlocalsym;
    unsigned int iextdefsym;
    unsigned int nextdefsym;
    unsigned int iundefsym;
    unsigned int nundefsym;
    unsigned int tocoff;
    unsigned int ntoc;
    unsigned int modtaboff;
    unsigned int nmodtab;
    unsigned int extrefsymoff;
    unsigned int nextrefsyms;
    unsigned int indirectsymoff;
    unsigned int nindirectsyms;
    unsigned int extreloff;
    unsigned int nextrel;
    unsigned int locreloff;
    unsigned int nlocrel;
};

struct encryption_info_command {
    unsigned int cmd;
    unsigned int cmdsize;
    unsigned int cryptoff;
    unsigned int cryptsize;
    unsigned int cryptid;
};

struct entry_point_command {
    unsigned int cmd;
    unsigned int cmdsize;
    unsigned long long entryoff;
    unsigned long long stacksize;
};

struct linkedit_data_command {
    unsigned int cmd;
    unsigned int cmdsize;
    unsigned int dataoff;
    unsigned int datasize;
};

struct load_command {
    unsigned int cmd;
    unsigned int cmdsize;
};

struct nlist {
    CDUnion_2f89ebda _field1;
    unsigned char _field2;
    unsigned char _field3;
    short _field4;
    unsigned int _field5;
};

struct nlist_64 {
    CDUnion_2f89ebda n_un;
    unsigned char n_type;
    unsigned char n_sect;
    unsigned short n_desc;
    unsigned long long n_value;
};

struct prebind_cksum_command {
    unsigned int cmd;
    unsigned int cmdsize;
    unsigned int cksum;
};

struct prebound_dylib_command {
    unsigned int cmd;
    unsigned int cmdsize;
    union lc_str name;
    unsigned int nmodules;
    union lc_str linked_modules;
};

struct relocation_info {
    int r_address;
    unsigned int r_symbolnum:24;
    unsigned int r_pcrel:1;
    unsigned int r_length:2;
    unsigned int r_extern:1;
    unsigned int r_type:4;
};

struct routines_command {
    unsigned int cmd;
    unsigned int cmdsize;
    unsigned int init_address;
    unsigned int init_module;
    unsigned int reserved1;
    unsigned int reserved2;
    unsigned int reserved3;
    unsigned int reserved4;
    unsigned int reserved5;
    unsigned int reserved6;
};

struct routines_command_64 {
    unsigned int cmd;
    unsigned int cmdsize;
    unsigned long long init_address;
    unsigned long long init_module;
    unsigned long long reserved1;
    unsigned long long reserved2;
    unsigned long long reserved3;
    unsigned long long reserved4;
    unsigned long long reserved5;
    unsigned long long reserved6;
};

struct rpath_command {
    unsigned int cmd;
    unsigned int cmdsize;
    union lc_str path;
};

struct section {
    char sectname[16];
    char segname[16];
    unsigned int addr;
    unsigned int size;
    unsigned int offset;
    unsigned int align;
    unsigned int reloff;
    unsigned int nreloc;
    unsigned int flags;
    unsigned int reserved1;
    unsigned int reserved2;
};

struct section_64 {
    char sectname[16];
    char segname[16];
    unsigned long long addr;
    unsigned long long size;
    unsigned int offset;
    unsigned int align;
    unsigned int reloff;
    unsigned int nreloc;
    unsigned int flags;
    unsigned int reserved1;
    unsigned int reserved2;
    unsigned int reserved3;
};

struct segment_command {
    unsigned int cmd;
    unsigned int cmdsize;
    char segname[16];
    unsigned int vmaddr;
    unsigned int vmsize;
    unsigned int fileoff;
    unsigned int filesize;
    int maxprot;
    int initprot;
    unsigned int nsects;
    unsigned int flags;
};

struct segment_command_64 {
    unsigned int cmd;
    unsigned int cmdsize;
    char segname[16];
    unsigned long long vmaddr;
    unsigned long long vmsize;
    unsigned long long fileoff;
    unsigned long long filesize;
    int maxprot;
    int initprot;
    unsigned int nsects;
    unsigned int flags;
};

struct source_version_command {
    unsigned int cmd;
    unsigned int cmdsize;
    unsigned long long version;
};

struct sub_client_command {
    unsigned int cmd;
    unsigned int cmdsize;
    union lc_str client;
};

struct sub_framework_command {
    unsigned int cmd;
    unsigned int cmdsize;
    union lc_str umbrella;
};

struct sub_library_command {
    unsigned int cmd;
    unsigned int cmdsize;
    union lc_str sub_library;
};

struct sub_umbrella_command {
    unsigned int cmd;
    unsigned int cmdsize;
    union lc_str sub_umbrella;
};

struct symtab_command {
    unsigned int cmd;
    unsigned int cmdsize;
    unsigned int symoff;
    unsigned int nsyms;
    unsigned int stroff;
    unsigned int strsize;
};

struct twolevel_hints_command {
    unsigned int cmd;
    unsigned int cmdsize;
    unsigned int offset;
    unsigned int nhints;
};

struct uuid_command {
    unsigned int cmd;
    unsigned int cmdsize;
    unsigned char uuid[16];
};

struct version_min_command {
    unsigned int cmd;
    unsigned int cmdsize;
    unsigned int version;
    unsigned int sdk;
};

#pragma mark Typedef'd Structures

typedef struct {
    int cputype;
    int cpusubtype;
} CDStruct_7a118b40;

#pragma mark Named Unions

union lc_str {
    unsigned int offset;
};

#pragma mark Typedef'd Unions

typedef union {
    unsigned int n_strx;
} CDUnion_2f89ebda;

