//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSScanner.h"

@interface NSScanner (CDExtensions)
+ (id)cdTemplateTypeCharacterSet;
+ (id)cdIdentifierCharacterSet;
+ (id)cdIdentifierStartCharacterSet;
+ (id)cdOtherCharacterSet;
- (BOOL)scanIdentifierIntoString:(id *)arg1;
- (BOOL)my_scanCharactersFromSet:(id)arg1 intoString:(id *)arg2;
- (BOOL)scanCharacterFromSet:(id)arg1 intoString:(id *)arg2;
- (BOOL)scanCharacter:(unsigned short *)arg1;
- (unsigned short)peekChar;
- (id)peekCharacter;
@end

