//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSMutableArray, NSMutableSet, NSString;

@interface CDOCProtocol : NSObject
{
    NSString *_name;
    NSMutableArray *_protocols;
    NSMutableArray *_classMethods;
    NSMutableArray *_instanceMethods;
    NSMutableArray *_optionalClassMethods;
    NSMutableArray *_optionalInstanceMethods;
    NSMutableArray *_properties;
    NSMutableSet *_adoptedProtocolNames;
}

@property(readonly, nonatomic) NSArray *properties; // @synthesize properties=_properties;
@property(readonly, nonatomic) NSArray *optionalInstanceMethods; // @synthesize optionalInstanceMethods=_optionalInstanceMethods;
@property(readonly, nonatomic) NSArray *optionalClassMethods; // @synthesize optionalClassMethods=_optionalClassMethods;
@property(readonly, nonatomic) NSArray *instanceMethods; // @synthesize instanceMethods=_instanceMethods;
@property(readonly, nonatomic) NSArray *classMethods; // @synthesize classMethods=_classMethods;
@property(readonly) NSArray *protocols; // @synthesize protocols=_protocols;
@property(retain) NSString *name; // @synthesize name=_name;
- (void).cxx_destruct;
- (void)mergePropertiesFromProtocol:(id)arg1;
- (void)mergeMethodsFromProtocol:(id)arg1;
- (void)visitMethods:(id)arg1 propertyState:(id)arg2;
- (void)recursivelyVisit:(id)arg1;
- (id)methodSearchContext;
- (long long)ascendingCompareByName:(id)arg1;
@property(readonly, nonatomic) NSString *sortableName;
- (void)registerTypesFromMethods:(id)arg1 withObject:(id)arg2 phase:(unsigned long long)arg3;
- (void)registerTypesWithObject:(id)arg1 phase:(unsigned long long)arg2;
@property(readonly, nonatomic) BOOL hasMethods;
- (void)addProperty:(id)arg1;
- (void)addOptionalInstanceMethod:(id)arg1;
- (void)addOptionalClassMethod:(id)arg1;
- (void)addInstanceMethod:(id)arg1;
- (void)addClassMethod:(id)arg1;
@property(readonly, nonatomic) NSString *protocolsString;
@property(readonly, nonatomic) NSArray *protocolNames;
- (void)removeProtocol:(id)arg1;
- (void)addProtocol:(id)arg1;
- (id)description;
- (id)init;

@end

