//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CDObjectiveCProcessor.h"

@interface CDObjectiveC2Processor : CDObjectiveCProcessor
{
}

- (id)objcImageInfoSection;
- (id)protocolAddressListAtAddress:(unsigned long long)arg1;
- (id)loadIvarsAtAddress:(unsigned long long)arg1;
- (id)loadMethodsAtAddress:(unsigned long long)arg1 extendedMethodTypesCursor:(id)arg2;
- (id)loadMethodsAtAddress:(unsigned long long)arg1;
- (id)loadMethodsOfMetaClassAtAddress:(unsigned long long)arg1;
- (id)loadPropertiesAtAddress:(unsigned long long)arg1;
- (id)loadClassAtAddress:(unsigned long long)arg1;
- (id)loadCategoryAtAddress:(unsigned long long)arg1;
- (id)protocolAtAddress:(unsigned long long)arg1;
- (void)loadCategories;
- (void)loadClasses;
- (void)loadProtocols;

@end

