//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CDOCProtocol.h"

#import "CDTopologicalSort.h"

@class NSArray, NSString;

@interface CDOCClass : CDOCProtocol <CDTopologicalSort>
{
    NSString *_superClassName;
    NSArray *_instanceVariables;
    BOOL _isExported;
}

@property BOOL isExported; // @synthesize isExported=_isExported;
@property(retain) NSArray *instanceVariables; // @synthesize instanceVariables=_instanceVariables;
@property(retain) NSString *superClassName; // @synthesize superClassName=_superClassName;
- (void).cxx_destruct;
@property(readonly, nonatomic) NSArray *dependancies;
@property(readonly, nonatomic) NSString *identifier;
- (void)recursivelyVisit:(id)arg1;
- (id)methodSearchContext;
- (void)registerTypesWithObject:(id)arg1 phase:(unsigned long long)arg2;
- (id)description;
- (id)init;

@end

