//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSString.h"

@interface NSString (CDExtensions)
+ (id)stringWithUnichar:(unsigned short)arg1;
+ (id)spacesIndentedToLevel:(unsigned long long)arg1 spacesPerLevel:(unsigned long long)arg2;
+ (id)spacesIndentedToLevel:(unsigned long long)arg1;
+ (id)stringWithFileSystemRepresentation:(const char *)arg1;
- (id)capitalizeFirstCharacter;
- (BOOL)hasUnderscoreCapitalPrefix;
- (id)SHA1DigestString;
- (id)executablePathForFilename;
- (void)print;
- (BOOL)isFirstLetterUppercase;
@end

