//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CDLoadCommand.h"

@class NSString;

@interface CDLCDylib : CDLoadCommand
{
    struct dylib_command _dylibCommand;
    NSString *_path;
}

@property(readonly) NSString *path; // @synthesize path=_path;
- (void).cxx_destruct;
@property(readonly, nonatomic) NSString *formattedCompatibilityVersion;
@property(readonly, nonatomic) NSString *formattedCurrentVersion;
@property(readonly, nonatomic) unsigned int compatibilityVersion;
@property(readonly, nonatomic) unsigned int currentVersion;
@property(readonly, nonatomic) unsigned int timestamp;
- (unsigned int)cmdsize;
- (unsigned int)cmd;
- (id)initWithDataCursor:(id)arg1;

@end

