//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class CDTypeLexer;

@interface CDTypeParser : NSObject
{
    CDTypeLexer *_lexer;
    int _lookahead;
}

@property(readonly) CDTypeLexer *lexer; // @synthesize lexer=_lexer;
- (void).cxx_destruct;
- (BOOL)isTokenInTypeStartSet:(int)arg1;
- (BOOL)isTokenInTypeSet:(int)arg1;
- (BOOL)isTokenInSimpleTypeSet:(int)arg1;
- (BOOL)isTokenInModifierSet:(int)arg1;
- (id)parseNumber;
- (id)parseIdentifier;
- (id)parseTypeName;
- (id)parseMember;
- (id)parseMemberList;
- (id)parseOptionalMembers;
- (id)parseUnionTypes;
- (id)_parseTypeInStruct:(BOOL)arg1;
- (id)_parseType;
- (id)_parseMethodType;
- (void)error:(id)arg1;
- (void)match:(int)arg1 enterState:(unsigned long long)arg2;
- (void)match:(int)arg1;
- (id)parseType:(id *)arg1;
- (id)parseMethodType:(id *)arg1;
- (id)initWithString:(id)arg1;

@end

