//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CDVisitor.h"

@class NSMutableString;

@interface CDTextClassDumpVisitor : CDVisitor
{
    NSMutableString *_resultString;
}

@property(readonly) NSMutableString *resultString; // @synthesize resultString=_resultString;
- (void).cxx_destruct;
- (void)_visitProperty:(id)arg1 parsedType:(id)arg2 attributes:(id)arg3;
- (void)writeResultToStandardOutput;
- (void)visitRemainingProperties:(id)arg1;
- (void)didVisitPropertiesOfProtocol:(id)arg1;
- (void)willVisitPropertiesOfProtocol:(id)arg1;
- (void)didVisitPropertiesOfCategory:(id)arg1;
- (void)willVisitPropertiesOfCategory:(id)arg1;
- (void)didVisitPropertiesOfClass:(id)arg1;
- (void)visitProperty:(id)arg1;
- (void)visitIvar:(id)arg1;
- (void)visitInstanceMethod:(id)arg1 propertyState:(id)arg2;
- (void)visitClassMethod:(id)arg1;
- (void)didVisitProtocol:(id)arg1;
- (void)willVisitOptionalMethods;
- (void)willVisitProtocol:(id)arg1;
- (void)didVisitCategory:(id)arg1;
- (void)willVisitCategory:(id)arg1;
- (void)didVisitIvarsOfClass:(id)arg1;
- (void)willVisitIvarsOfClass:(id)arg1;
- (void)didVisitClass:(id)arg1;
- (void)willVisitClass:(id)arg1;
- (id)init;

@end

