//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class CDTypeController;

@interface CDTypeFormatter : NSObject
{
    CDTypeController *_typeController;
    unsigned long long _baseLevel;
    BOOL _shouldExpand;
    BOOL _shouldAutoExpand;
    BOOL _shouldShowLexing;
}

@property BOOL shouldShowLexing; // @synthesize shouldShowLexing=_shouldShowLexing;
@property BOOL shouldAutoExpand; // @synthesize shouldAutoExpand=_shouldAutoExpand;
@property BOOL shouldExpand; // @synthesize shouldExpand=_shouldExpand;
@property unsigned long long baseLevel; // @synthesize baseLevel=_baseLevel;
@property __weak CDTypeController *typeController; // @synthesize typeController=_typeController;
- (void).cxx_destruct;
- (void)formattingDidReferenceClassName:(id)arg1;
- (id)typedefNameForStructure:(id)arg1 level:(unsigned long long)arg2;
- (id)replacementForType:(id)arg1;
- (id)formatMethodName:(id)arg1 typeString:(id)arg2;
- (id)formattedTypesForMethodName:(id)arg1 type:(id)arg2;
- (id)formatVariable:(id)arg1 type:(id)arg2;
- (id)_specialCaseVariable:(id)arg1 parsedType:(id)arg2;
- (id)_specialCaseVariable:(id)arg1 type:(id)arg2;
- (id)description;
- (id)init;

@end

