//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CDLCSegment.h"

@interface CDLCSegment64 : CDLCSegment
{
    struct segment_command_64 _segmentCommand;
}

- (id)extraDescription;
- (BOOL)containsAddress:(unsigned long long)arg1;
- (unsigned int)flags;
- (int)initprot;
- (unsigned long long)filesize;
- (unsigned long long)fileoff;
- (unsigned long long)vmaddr;
- (unsigned int)cmdsize;
- (unsigned int)cmd;
- (id)initWithDataCursor:(id)arg1;

@end

