//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CDLoadCommand.h"

@interface CDLCEncryptionInfo : CDLoadCommand
{
    struct encryption_info_command _encryptionInfoCommand;
    unsigned int _pad;
}

@property(readonly, nonatomic) BOOL isEncrypted;
@property(readonly, nonatomic) unsigned int cryptid;
@property(readonly, nonatomic) unsigned int cryptsize;
@property(readonly, nonatomic) unsigned int cryptoff;
- (unsigned int)cmdsize;
- (unsigned int)cmd;
- (id)initWithDataCursor:(id)arg1;

@end

