//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CDOCProtocol.h"

#import "CDTopologicalSort.h"

@class NSArray, NSString;

@interface CDOCCategory : CDOCProtocol <CDTopologicalSort>
{
    NSString *_className;
}

@property(retain) NSString *className; // @synthesize className=_className;
- (void).cxx_destruct;
@property(readonly, nonatomic) NSArray *dependancies;
@property(readonly, nonatomic) NSString *identifier;
- (void)recursivelyVisit:(id)arg1;
- (id)methodSearchContext;
- (id)sortableName;

@end

