//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSData, NSString;

@interface CDSection : NSObject
{
    NSString *_segmentName;
    NSString *_sectionName;
    NSData *_data;
    BOOL _hasLoadedData;
}

@property BOOL hasLoadedData; // @synthesize hasLoadedData=_hasLoadedData;
@property(retain, nonatomic) NSData *data; // @synthesize data=_data;
@property(retain) NSString *sectionName; // @synthesize sectionName=_sectionName;
@property(retain) NSString *segmentName; // @synthesize segmentName=_segmentName;
- (void).cxx_destruct;
- (unsigned long long)fileOffsetForAddress:(unsigned long long)arg1;
- (BOOL)containsAddress:(unsigned long long)arg1;
- (id)machOFile;
@property(readonly, nonatomic) unsigned long long size;
@property(readonly, nonatomic) unsigned long long addr;
- (void)unloadData;
- (void)loadData;
- (id)description;

@end

