//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSMutableString.h"

@interface NSMutableString (CDExtensions)
- (void)appendSpacesIndentedToLevel:(unsigned long long)arg1 spacesPerLevel:(unsigned long long)arg2;
- (void)appendSpacesIndentedToLevel:(unsigned long long)arg1;
@end

