//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CDLoadCommand.h"

@class NSArray, NSMutableData, NSString;

@interface CDLCSegment : CDLoadCommand
{
    NSString *_name;
    NSArray *_sections;
    NSMutableData *_decryptedData;
}

@property(retain) NSArray *sections; // @synthesize sections=_sections;
@property(retain) NSString *name; // @synthesize name=_name;
- (void).cxx_destruct;
- (id)decryptedData;
- (void)writeSectionData;
- (void)appendToString:(id)arg1 verbose:(BOOL)arg2;
- (unsigned long long)segmentOffsetForAddress:(unsigned long long)arg1;
- (unsigned long long)fileOffsetForAddress:(unsigned long long)arg1;
- (id)sectionWithName:(id)arg1;
- (id)sectionContainingAddress:(unsigned long long)arg1;
- (BOOL)containsAddress:(unsigned long long)arg1;
- (id)flagDescription;
@property(readonly, nonatomic) BOOL canDecrypt;
@property(readonly, nonatomic) unsigned long long encryptionType;
@property(readonly, nonatomic) BOOL isProtected;
@property(readonly, nonatomic) unsigned int flags;
@property(readonly, nonatomic) int initprot;
@property(readonly, nonatomic) unsigned long long filesize;
@property(readonly, nonatomic) unsigned long long fileoff;
@property(readonly, nonatomic) unsigned long long vmaddr;
- (id)extraDescription;
- (id)description;
- (id)initWithDataCursor:(id)arg1;

@end

