//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCopying.h"

@class NSArray, NSString;

@interface CDOCMethod : NSObject <NSCopying>
{
    NSString *_name;
    NSString *_typeString;
    unsigned long long _address;
    BOOL _hasParsedType;
    NSArray *_parsedMethodTypes;
}

@property unsigned long long address; // @synthesize address=_address;
@property(readonly) NSString *typeString; // @synthesize typeString=_typeString;
@property(readonly) NSString *name; // @synthesize name=_name;
- (void).cxx_destruct;
- (long long)ascendingCompareByName:(id)arg1;
- (void)appendToString:(id)arg1 typeController:(id)arg2;
- (id)parsedMethodTypes;
- (id)description;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)initWithName:(id)arg1 typeString:(id)arg2 address:(unsigned long long)arg3;
- (id)initWithName:(id)arg1 typeString:(id)arg2;
- (id)init;

@end

