//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableDictionary;

@interface CDProtocolUniquer : NSObject
{
    NSMutableDictionary *_protocolsByAddress;
    NSMutableDictionary *_uniqueProtocolsByName;
    NSMutableDictionary *_uniqueProtocolsByAddress;
}

- (void).cxx_destruct;
- (id)uniqueProtocolsSortedByName;
- (id)uniqueProtocolsAtAddresses:(id)arg1;
- (void)createUniquedProtocols;
- (void)setProtocol:(id)arg1 withAddress:(unsigned long long)arg2;
- (id)protocolWithAddress:(unsigned long long)arg1;
- (id)init;

@end

