//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSMutableDictionary;

@interface CDVisitorPropertyState : NSObject
{
    NSMutableDictionary *_propertiesByAccessor;
    NSMutableDictionary *_propertiesByName;
}

- (void).cxx_destruct;
@property(readonly, nonatomic) NSArray *remainingProperties;
- (void)useProperty:(id)arg1;
- (BOOL)hasUsedProperty:(id)arg1;
- (id)propertyForAccessor:(id)arg1;
- (void)log;
- (id)initWithProperties:(id)arg1;

@end

