//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class CDSearchPathState, NSData, NSString;

@interface CDFile : NSObject
{
    NSString *_filename;
    NSData *_data;
    CDSearchPathState *_searchPathState;
}

+ (id)fileWithContentsOfFile:(id)arg1 searchPathState:(id)arg2;
@property(readonly) CDSearchPathState *searchPathState; // @synthesize searchPathState=_searchPathState;
@property(readonly) NSData *data; // @synthesize data=_data;
@property(readonly) NSString *filename; // @synthesize filename=_filename;
- (void).cxx_destruct;
@property(readonly, nonatomic) NSString *architectureNameDescription;
- (id)machOFileWithArch:(CDStruct_7a118b40)arg1;
- (BOOL)bestMatchForArch:(CDStruct_7a118b40 *)arg1;
- (BOOL)bestMatchForLocalArch:(CDStruct_7a118b40 *)arg1;
- (id)initWithData:(id)arg1 filename:(id)arg2 searchPathState:(id)arg3;

@end

