//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CDLoadCommand.h"

@class NSData;

@interface CDLCLinkeditData : CDLoadCommand
{
    struct linkedit_data_command _linkeditDataCommand;
    NSData *_linkeditData;
}

- (void).cxx_destruct;
@property(readonly, nonatomic) NSData *linkeditData;
- (unsigned int)cmdsize;
- (unsigned int)cmd;
- (id)initWithDataCursor:(id)arg1;

@end

