//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class CDMachOFile, CDProtocolUniquer, CDSection, NSMutableArray, NSMutableDictionary, NSString;

@interface CDObjectiveCProcessor : NSObject
{
    CDMachOFile *_machOFile;
    NSMutableArray *_classes;
    NSMutableDictionary *_classesByAddress;
    NSMutableArray *_categories;
    CDProtocolUniquer *_protocolUniquer;
}

@property(readonly) CDProtocolUniquer *protocolUniquer; // @synthesize protocolUniquer=_protocolUniquer;
@property(readonly) CDMachOFile *machOFile; // @synthesize machOFile=_machOFile;
- (void).cxx_destruct;
- (id)protocolAddressListAtAddress:(unsigned long long)arg1;
- (void)recursivelyVisit:(id)arg1;
- (void)registerTypesWithObject:(id)arg1 phase:(unsigned long long)arg2;
- (void)loadCategories;
- (void)loadClasses;
- (void)loadProtocols;
- (void)process;
- (void)addCategory:(id)arg1;
- (void)addCategoriesFromArray:(id)arg1;
- (void)addClassesFromArray:(id)arg1;
- (id)classWithAddress:(unsigned long long)arg1;
- (void)addClass:(id)arg1 withAddress:(unsigned long long)arg2;
@property(readonly, nonatomic) NSString *garbageCollectionStatus;
@property(readonly, nonatomic) CDSection *objcImageInfoSection;
@property(readonly, nonatomic) BOOL hasObjectiveCData;
- (id)description;
- (id)initWithMachOFile:(id)arg1;

@end

