//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class CDType, NSArray, NSMutableArray, NSString;

@interface CDOCProperty : NSObject
{
    NSString *_name;
    NSString *_attributeString;
    CDType *_type;
    NSMutableArray *_attributes;
    BOOL _hasParsedAttributes;
    NSString *_attributeStringAfterType;
    NSString *_customGetter;
    NSString *_customSetter;
    BOOL _isReadOnly;
    BOOL _isDynamic;
}

@property(readonly) BOOL isDynamic; // @synthesize isDynamic=_isDynamic;
@property(readonly) BOOL isReadOnly; // @synthesize isReadOnly=_isReadOnly;
@property(retain) NSString *customSetter; // @synthesize customSetter=_customSetter;
@property(retain) NSString *customGetter; // @synthesize customGetter=_customGetter;
@property(retain) NSString *attributeStringAfterType; // @synthesize attributeStringAfterType=_attributeStringAfterType;
@property(readonly) NSArray *attributes; // @synthesize attributes=_attributes;
@property(readonly) CDType *type; // @synthesize type=_type;
@property(readonly) NSString *attributeString; // @synthesize attributeString=_attributeString;
@property(readonly) NSString *name; // @synthesize name=_name;
- (void).cxx_destruct;
- (void)_parseAttributes;
- (long long)ascendingCompareByName:(id)arg1;
@property(readonly, nonatomic) NSString *setter;
@property(readonly, nonatomic) NSString *getter;
@property(readonly, nonatomic) NSString *defaultSetter;
@property(readonly, nonatomic) NSString *defaultGetter;
- (id)description;
- (id)initWithName:(id)arg1 attributes:(id)arg2;

@end

