//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSData;

@interface CDDataCursor : NSObject
{
    NSData *_data;
    unsigned long long _offset;
}

@property(nonatomic) unsigned long long offset; // @synthesize offset=_offset;
@property(readonly) NSData *data; // @synthesize data=_data;
- (void).cxx_destruct;
- (id)readStringOfLength:(unsigned long long)arg1 encoding:(unsigned long long)arg2;
- (id)readCString;
- (BOOL)isAtEnd;
- (void)readBytesOfLength:(unsigned long long)arg1 intoBuffer:(void *)arg2;
- (void)appendBytesOfLength:(unsigned long long)arg1 intoData:(id)arg2;
- (double)readLittleFloat64;
- (float)readBigFloat32;
- (float)readLittleFloat32;
- (unsigned long long)readBigInt64;
- (unsigned int)readBigInt32;
- (unsigned short)readBigInt16;
- (unsigned long long)readLittleInt64;
- (unsigned int)readLittleInt32;
- (unsigned short)readLittleInt16;
- (unsigned char)readByte;
- (unsigned long long)remaining;
- (void)advanceByLength:(unsigned long long)arg1;
- (const void *)bytes;
- (id)initWithData:(id)arg1;

@end

