//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class CDMachOFile, NSString;

@interface CDLoadCommand : NSObject
{
    CDMachOFile *_machOFile;
    unsigned long long _commandOffset;
}

+ (id)loadCommandWithDataCursor:(id)arg1;
@property(readonly) unsigned long long commandOffset; // @synthesize commandOffset=_commandOffset;
@property(readonly) CDMachOFile *machOFile; // @synthesize machOFile=_machOFile;
- (void).cxx_destruct;
- (void)machOFileDidReadLoadCommands:(id)arg1;
- (void)appendToString:(id)arg1 verbose:(BOOL)arg2;
@property(readonly, nonatomic) NSString *commandName;
@property(readonly, nonatomic) BOOL mustUnderstandToExecute;
@property(readonly, nonatomic) unsigned int cmdsize;
@property(readonly, nonatomic) unsigned int cmd;
- (id)extraDescription;
- (id)description;
- (id)initWithDataCursor:(id)arg1;

@end

