//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSScanner, NSString;

@interface CDTypeLexer : NSObject
{
    NSScanner *_scanner;
    unsigned long long _state;
    NSString *_lexText;
    BOOL _shouldShowLexing;
}

@property(retain) NSString *lexText; // @synthesize lexText=_lexText;
@property BOOL shouldShowLexing; // @synthesize shouldShowLexing=_shouldShowLexing;
@property(nonatomic) unsigned long long state; // @synthesize state=_state;
@property(readonly) NSScanner *scanner; // @synthesize scanner=_scanner;
- (void).cxx_destruct;
@property(readonly, nonatomic) NSString *peekIdentifier;
@property(readonly, nonatomic) NSString *remainingString;
@property(readonly, nonatomic) unsigned short peekChar;
- (int)scanNextToken;
@property(readonly, nonatomic) NSString *string;
- (id)initWithString:(id)arg1;

@end

