//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CDDataCursor.h"

@class CDMachOFile;

@interface CDMachOFileDataCursor : CDDataCursor
{
    CDMachOFile *_machOFile;
}

@property(readonly) CDMachOFile *machOFile; // @synthesize machOFile=_machOFile;
- (void).cxx_destruct;
- (unsigned long long)readPtr;
- (unsigned int)peekInt32;
- (unsigned long long)readInt64;
- (unsigned int)readInt32;
- (unsigned short)readInt16;
- (void)setAddress:(unsigned long long)arg1;
- (id)initWithSection:(id)arg1;
- (id)initWithFile:(id)arg1 address:(unsigned long long)arg2;
- (id)initWithFile:(id)arg1 offset:(unsigned long long)arg2;
- (id)initWithFile:(id)arg1;

@end

