//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CDTextClassDumpVisitor.h"

#import "CDTypeControllerDelegate.h"

@class NSArray, NSDictionary, NSMutableSet, NSString;

@interface CDMultiFileVisitor : CDTextClassDumpVisitor <CDTypeControllerDelegate>
{
    NSString *_outputPath;
    NSDictionary *_frameworkNamesByClassName;
    NSMutableSet *_referencedClassNames;
    NSMutableSet *_referencedProtocolNames;
    unsigned long long _referenceLocation;
}

@property(readonly) NSMutableSet *referencedProtocolNames; // @synthesize referencedProtocolNames=_referencedProtocolNames;
@property(readonly) NSMutableSet *referencedClassNames; // @synthesize referencedClassNames=_referencedClassNames;
@property unsigned long long referenceLocation; // @synthesize referenceLocation=_referenceLocation;
@property(retain) NSDictionary *frameworkNamesByClassName; // @synthesize frameworkNamesByClassName=_frameworkNamesByClassName;
@property(retain) NSString *outputPath; // @synthesize outputPath=_outputPath;
- (void).cxx_destruct;
- (void)generateStructureHeader;
- (void)buildClassFrameworks;
@property(readonly, nonatomic) NSString *referenceString;
- (void)createOutputPathIfNecessary;
- (void)removeAllClassNameProtocolNameReferences;
- (void)addReferencesToProtocolNamesInArray:(id)arg1;
- (void)removeReferenceToClassName:(id)arg1;
- (void)addReferenceToClassName:(id)arg1;
@property(readonly, nonatomic) NSArray *referencedProtocolNamesSortedByName;
@property(readonly, nonatomic) NSArray *referencedClassNamesSortedByName;
- (id)importStringForProtocolName:(id)arg1;
- (id)importStringForClassName:(id)arg1;
- (id)frameworkForProtocolName:(id)arg1;
- (id)frameworkForClassName:(id)arg1;
- (void)typeController:(id)arg1 didReferenceClassName:(id)arg2;
- (void)didVisitProtocol:(id)arg1;
- (void)willVisitProtocol:(id)arg1;
- (void)didVisitCategory:(id)arg1;
- (void)willVisitCategory:(id)arg1;
- (void)didVisitClass:(id)arg1;
- (void)willVisitClass:(id)arg1;
- (void)willBeginVisiting;
- (id)init;

@end

