//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCopying.h"

@class CDType, NSString;

@interface CDStructureInfo : NSObject <NSCopying>
{
    CDType *_type;
    unsigned long long _referenceCount;
    BOOL _isUsedInMethod;
    NSString *_typedefName;
}

@property(retain) NSString *typedefName; // @synthesize typedefName=_typedefName;
@property BOOL isUsedInMethod; // @synthesize isUsedInMethod=_isUsedInMethod;
@property unsigned long long referenceCount; // @synthesize referenceCount=_referenceCount;
@property(readonly) CDType *type; // @synthesize type=_type;
- (void).cxx_destruct;
- (long long)descendingCompareByStructureDepth:(id)arg1;
- (long long)ascendingCompareByStructureDepth:(id)arg1;
@property(readonly, nonatomic) NSString *name;
- (void)generateTypedefName:(id)arg1;
- (void)addReferenceCount:(unsigned long long)arg1;
- (id)shortDescription;
- (id)description;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)initWithType:(id)arg1;

@end

