//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class CDFatFile, CDMachOFile, NSString;

@interface CDFatArch : NSObject
{
    CDFatFile *_fatFile;
    int _cputype;
    int _cpusubtype;
    unsigned int _offset;
    unsigned int _size;
    unsigned int _align;
    CDMachOFile *_machOFile;
}

@property __weak CDFatFile *fatFile; // @synthesize fatFile=_fatFile;
@property unsigned int align; // @synthesize align=_align;
@property unsigned int size; // @synthesize size=_size;
@property unsigned int offset; // @synthesize offset=_offset;
@property int cpusubtype; // @synthesize cpusubtype=_cpusubtype;
@property int cputype; // @synthesize cputype=_cputype;
- (void).cxx_destruct;
@property(readonly, nonatomic) CDMachOFile *machOFile;
@property(readonly, nonatomic) NSString *archName;
@property(readonly, nonatomic) CDStruct_7a118b40 arch;
@property(readonly, nonatomic) BOOL uses64BitLibraries;
@property(readonly, nonatomic) BOOL uses64BitABI;
@property(readonly, nonatomic) int maskedCPUSubtype;
@property(readonly, nonatomic) int maskedCPUType;
- (id)description;
- (id)initWithDataCursor:(id)arg1;
- (id)initWithMachOFile:(id)arg1;

@end

