//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class CDTypeController, NSMutableArray, NSMutableDictionary, NSMutableSet, NSString;

@interface CDStructureTable : NSObject
{
    CDTypeController *_typeController;
    NSString *_identifier;
    NSString *_anonymousBaseName;
    NSMutableDictionary *_phase0_structureInfo;
    NSMutableDictionary *_phase1_structureInfo;
    unsigned long long _phase1_maxDepth;
    NSMutableDictionary *_phase1_groupedByDepth;
    NSMutableDictionary *_phase2_namedStructureInfo;
    NSMutableDictionary *_phase2_anonStructureInfo;
    NSMutableArray *_phase2_nameExceptions;
    NSMutableArray *_phase2_anonExceptions;
    NSMutableDictionary *_phase3_namedStructureInfo;
    NSMutableDictionary *_phase3_anonStructureInfo;
    NSMutableDictionary *_phase3_nameExceptions;
    NSMutableDictionary *_phase3_anonExceptions;
    NSMutableSet *_phase3_exceptionalNames;
    NSMutableSet *_phase3_inMethodNameExceptions;
    BOOL _shouldDebug;
    NSMutableSet *_debugNames;
    NSMutableSet *_debugAnon;
}

@property __weak CDTypeController *typeController; // @synthesize typeController=_typeController;
@property BOOL shouldDebug; // @synthesize shouldDebug=_shouldDebug;
@property(retain) NSString *anonymousBaseName; // @synthesize anonymousBaseName=_anonymousBaseName;
@property(retain) NSString *identifier; // @synthesize identifier=_identifier;
- (void).cxx_destruct;
- (void)logPhase3Info;
- (void)logPhase2Info;
- (void)logPhase0Info;
- (void)debugAnon:(id)arg1;
- (void)debugName:(id)arg1;
- (id)typedefNameForType:(id)arg1;
- (BOOL)shouldExpandType:(id)arg1;
- (BOOL)shouldExpandStructureInfo:(id)arg1;
- (void)appendTypedefsToString:(id)arg1 formatter:(id)arg2 markName:(id)arg3;
- (void)appendNamedStructuresToString:(id)arg1 formatter:(id)arg2 markName:(id)arg3;
- (void)generateMemberNames;
- (void)generateTypedefNames;
- (id)phase3ReplacementForType:(id)arg1;
- (void)finishPhase3;
- (void)phase3RegisterStructure:(id)arg1 count:(unsigned long long)arg2 usedInMethod:(BOOL)arg3;
- (void)runPhase3;
- (void)buildPhase3Exceptions;
- (void)phase2ReplacementOnPhase0;
- (void)finishPhase2;
- (id)phase2ReplacementForType:(id)arg1;
- (void)runPhase2AtDepth:(unsigned long long)arg1;
@property(readonly, nonatomic) unsigned long long phase1_maxDepth;
- (void)finishPhase1;
- (void)phase1RegisterStructure:(id)arg1;
- (void)runPhase1;
- (void)finishPhase0;
- (void)phase0RegisterStructure:(id)arg1 usedInMethod:(BOOL)arg2;
- (id)init;

@end

